# Generated by Django 5.2.13 on 2026-06-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_alter_objecttype_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="objecttypeversion",
            name="strict_format_checker",
            field=models.BooleanField(
                help_text="When enabled, JSON Schema validation enforces format constraints Defaults to the JSONSCHEMA_USE_FORMAT_CHECKER setting.",
                null=True,
            ),
        ),
    ]
