# Generated by Django 5.2.15 on 2026-06-23 14:08
import objects.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_alter_objecttype_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="objecttypeversion",
            name="strict_format_checker",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "When enabled, JSON Schema validation enforces format constraints. "
                    "Defaults to the JSONSCHEMA_USE_FORMAT_CHECKER setting."
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="objecttypeversion",
            name="strict_format_checker",
            field=models.BooleanField(
                default=objects.core.utils.get_strict_format_checker_default,
                help_text="When enabled, JSON Schema validation enforces format constraints. Defaults to the JSONSCHEMA_USE_FORMAT_CHECKER setting.",
            ),
        ),
    ]
